# Generated by Django 5.0.7 on 2024-07-24 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment', models.BigIntegerField(blank=True, null=True, verbose_name='Номер записи')),
                ('operation_id', models.CharField(max_length=255, unique=True, verbose_name='ID операции')),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Сумма')),
                ('is_success', models.BooleanField(blank=True, null=True, verbose_name='Успешно')),
            ],
            options={
                'verbose_name': 'Платеж',
                'verbose_name_plural': 'Платежи',
            },
        ),
    ]
