# Generated by Django 5.0.7 on 2024-07-25 02:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beauty_salons', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appointment',
            options={'verbose_name': 'Запись', 'verbose_name_plural': 'Записи'},
        ),
    ]
