# Generated by Django 5.0.7 on 2024-07-29 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beauty_salons', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='master',
            name='experience',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Стаж работы'),
        ),
        migrations.AddField(
            model_name='master',
            name='reviews',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Отзывы'),
        ),
    ]
