# Generated by Django 5.0.7 on 2024-07-25 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beauty_salons', '0002_alter_appointment_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salon',
            name='image',
            field=models.ImageField(blank=True, upload_to='salons_images/', verbose_name='Изображение'),
        ),
    ]
