# Generated by Django 5.0.7 on 2024-07-25 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beauty_salons', '0003_alter_salon_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='master',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='masters_images/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='service',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='services_images/', verbose_name='Изображение'),
        ),
    ]
