# Generated by Django 5.0.7 on 2024-07-26 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beauty_salons', '0007_customer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Customer',
        ),
        migrations.RenameField(
            model_name='customuser',
            old_name='phonenumber',
            new_name='phone_number',
        ),
        migrations.AddField(
            model_name='customuser',
            name='pin',
            field=models.CharField(max_length=4, null=True, verbose_name='код'),
        ),
    ]
