# Generated by Django 5.0.7 on 2024-07-27 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beauty_salons', '0008_delete_customer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pay',
            name='_type',
            field=models.CharField(blank=True, choices=[('tips', 'Чаевые'), ('service', 'Услуга')], max_length=255, null=True, verbose_name='Тип'),
        ),
    ]
